### ISSUE TITLE
Still Doesn't work

### ISSUE THREAD

**Issue by mintdotco** [scratchminer/Index-OS#14]
Gives the same error, just tried again today after updating to the new release 
[crashlog.txt](https://github.com/scratchminer/Index-OS/files/12449051/crashlog.txt)
[errorlog.txt](https://github.com/scratchminer/Index-OS/files/12449052/errorlog.txt)

**Comment by scratchminer** [comment]
You're on Index version 1.1.8, correct? I forgot to make the release the latest one when publishing it, so if you downloaded it earlier today you still might have gotten v1.1.7

**Comment by mintdotco** [comment]
I'll try it again but it seems to be 1.1.8

**Comment by mintdotco** [comment]
Yup, 1.1.8, I checked

**Comment by mintdotco** [comment]
Did you figure it out?

**Comment by scratchminer** [comment]
The issue seems to be related to the different addresses for Revision B Playdates, and until I manage to get my hands on the Revision B firmware, I probably won't be able to fix the issue. You can test it on the official Simulator (downloadable from [https://play.date/dev](https://play.date/dev) until then.)

**Comment by mintdotco** [comment]
Well, that kinda sucks. Hope you figure it out! :)
