### ISSUE TITLE
Some games launcher card images not displayed

### ISSUE THREAD

**Issue by R0M4N0F5K7** [scratchminer/Index-OS#9]
Some games launcher card images are not displayed and the launcher falls back to just display a black card with the game title.
The games are 'Simorgh', 'PlayGB' and 'aliens ate my boyfriend'.
Reinstalling didn't fix it. In original OS they are displayed.

**Comment by scratchminer** [comment]
I can't reproduce this issue. Can you please check the game bundle's `pdxinfo` file, to see if `imagePath` points to the correct place?

**Comment by raewtf** [comment]
i think it's games that point to a specific image for their launcher card data rather than a folder that causes it? within my sideload library, it happens with smolitaire and ash K's pomodoro timer (both free on itch for testing purposes) - pomodoro points to "cover" for its image (the card image is 'cover.pdi', located at the root), and smolitaire points to "launch/beta-card.png" for its imagepath, and the card is located at...well, take a guess LOL. any other game in my library points to the folder that the card is in rather than the image itself, and all of those render just fine
it's worth taking a look at snak from the season and seeing if that has the issue too, cuz i believe it has the same "point straight to the image" approach

**Comment by raewtf** [comment]
![snak](https://github.com/scratchminer/Index-OS/assets/114977596/51b7d31e-c490-4dd9-a58e-f6a037961f4d)
well that's quite the wrench? snak does use the same sorta deal - imagepath=card ; the actual image is at card.pdi on the root, yet it works. is it something to do with sideloading? 
edit: oh, derp, it's because pomodoro's using "cover" as its name for some dumb reason. changing that one's filename to "card" makes it work just fine even on the root

**Comment by scratchminer** [comment]
I found the problem. It's [here](https://github.com/scratchminer/Index-OS/blob/9f1735ffddf6e2bdc9f6d66413118a1bbf4281c4/Source/game.lua#L279) in `game.lua`. I'll push a fix
